import { ReactNode } from "react";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import { geistMono, geistSans } from "@/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Marketing Al Día",
    default: "MAD Website",
  },
  description: "Generated by create next app",
  creator: "Ziphonex Tech",
  generator: "Clean Native Code",
  applicationName: "MAD Website",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
  },
  alternates: {
    canonical: "https://www.marketingaldia.net",
    languages: {
      "es-PE": "/es-PE",
    },
  },
  verification: {
    google: "google",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="es-PE">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          color="#000c25"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #000c25,0 0 5px #000c25"
          showAtBottom={true}
        />
        {children}
      </body>
    </html>
  );
}
